model: 
  path: "./models/yolo12n.pt"
  conf: 0.7
  agnostic_nms: true
  single_cls: true
  classes: [0]
  frame_freq: 5
  
reid:
  max_age: 10
  n_init: 3
  nn_budget: 100

protocol: "udp"

server:
  host: "localhost"
  port: 8888
  buffer_size: 100000
  socket_timeout: 0

instances:
  - name: "camera_1"
    video: "./videos/4p-c0.avi"
    transmission:
      host: "localhost"
      port: 5001
  - name: "camera_2"
    video: "./videos/4p-c1.avi"
    transmission:
      host: "localhost"
      port: 5002

